// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WebMetadata { browser: string, browserVersion: string, os: string, osVersion: string, }