volumes:
  timescaledb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./target
  timescaledb_backups:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./backups
  timescaledb_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./logs
  timescaledb_pgbackrest_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./config
  custom_entrypoint:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./scripts/custom_entrypoint.sh
  

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg15-ts2.10
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/home/postgres/pgdata
      - timescaledb_backups:/var/lib/pgbackrest
      - timescaledb_pgbackrest_config:/home/postgres/pgdata/backup
      - timescaledb_logs:/var/log
      - .custom_entrypoint:/docker-entrypoint-initdb.d/custom_entrypoint.sh
    entrypoint: ["/docker-entrypoint-initdb.d/custom_entrypoint.sh"]
    restart: no
    environment:
      ENV: DEV
      POSTGRES_USER: admin1234
      POSTGRES_PASSWORD: password12345
      POSTGRES_DB: connect_db
      PG_DATA: /home/postgres/pgdata
      PGUSER: admin1234
      # PGBACKREST_REPO_PATH: /home/postgres/pgdata/backup
      # PGBACKREST_STANZA: db
      # PGBACKREST_LOG_PATH: /home/postgres/pgdata/backup/log
    # command: ["/bin/bash", "-c", "postgres -D $PG_DATA >logfile 2>&1 & sleep infinity"]


