version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    ports:
      - 5432:5432
    volumes:
      - ./target:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TIMESCALEDB_TELEMETRY=off
