volumes:
  timescaledb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./target
  timescaledb_backups:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./backups
  timescaledb_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./logs
  timescaledb_pgbackrest_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./config

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg15-ts2.10
    ports:
      - 5432:5432
    volumes:
      - timescaledb_data:/home/postgres/pgdata
      - timescaledb_backups:/var/lib/pgbackrest
      - timescaledb_pgbackrest_config:/home/postgres/pgdata/backup
      - timescaledb_logs:/var/log
      - ./scripts/custom_entrypoint.sh:/usr/local/bin/custom_entrypoint.sh
    entrypoint: ["/usr/local/bin/custom_entrypoint.sh"]
    command: ["postgres"]
    restart: no
    environment:
      ENV: DEV
      POSTGRES_USER: admin1234
      POSTGRES_PASSWORD: password12345
      POSTGRES_DB: connect_db
      PG_DATA: /home/postgres/pgdata
      PGUSER: admin1234


