/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddServiceAccountTokenCommand {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "secondsToLive", skip_serializing_if = "Option::is_none")]
    pub seconds_to_live: Option<i64>,
}

impl AddServiceAccountTokenCommand {
    pub fn new() -> AddServiceAccountTokenCommand {
        AddServiceAccountTokenCommand {
            name: None,
            seconds_to_live: None,
        }
    }
}

