/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AddDataSourceCommand : Also acts as api DTO
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDataSourceCommand {
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[serde(rename = "basicAuth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<bool>,
    #[serde(rename = "basicAuthUser", skip_serializing_if = "Option::is_none")]
    pub basic_auth_user: Option<String>,
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(rename = "jsonData", skip_serializing_if = "Option::is_none")]
    pub json_data: Option<serde_json::Value>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "secureJsonData", skip_serializing_if = "Option::is_none")]
    pub secure_json_data: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    #[serde(rename = "withCredentials", skip_serializing_if = "Option::is_none")]
    pub with_credentials: Option<bool>,
}

impl AddDataSourceCommand {
    /// Also acts as api DTO
    pub fn new() -> AddDataSourceCommand {
        AddDataSourceCommand {
            access: None,
            basic_auth: None,
            basic_auth_user: None,
            database: None,
            is_default: None,
            json_data: None,
            name: None,
            secure_json_data: None,
            r#type: None,
            uid: None,
            url: None,
            user: None,
            with_credentials: None,
        }
    }
}

