/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AlertingRule : adapted from cortex
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertingRule {
    #[serde(rename = "activeAt")]
    pub active_at: String,
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<Vec<models::Alert>>,
    /// The custom marshaling for labels.Labels ends up doing this anyways.
    #[serde(rename = "annotations")]
    pub annotations: std::collections::HashMap<String, String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "evaluationTime", skip_serializing_if = "Option::is_none")]
    pub evaluation_time: Option<f64>,
    #[serde(rename = "health")]
    pub health: String,
    /// The custom marshaling for labels.Labels ends up doing this anyways.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "lastError", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "lastEvaluation", skip_serializing_if = "Option::is_none")]
    pub last_evaluation: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "query")]
    pub query: String,
    /// State can be \"pending\", \"firing\", \"inactive\".
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<std::collections::HashMap<String, i64>>,
    #[serde(rename = "totalsFiltered", skip_serializing_if = "Option::is_none")]
    pub totals_filtered: Option<std::collections::HashMap<String, i64>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AlertingRule {
    /// adapted from cortex
    pub fn new(active_at: String, annotations: std::collections::HashMap<String, String>, health: String, name: String, query: String, state: String, r#type: String) -> AlertingRule {
        AlertingRule {
            active_at,
            alerts: None,
            annotations,
            duration: None,
            evaluation_time: None,
            health,
            labels: None,
            last_error: None,
            last_evaluation: None,
            name,
            query,
            state,
            totals: None,
            totals_filtered: None,
            r#type,
        }
    }
}

