/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrg200Response {
    /// Message Message of the created org.
    #[serde(rename = "message")]
    pub message: String,
    /// ID Identifier of the created org.
    #[serde(rename = "orgId")]
    pub org_id: i64,
}

impl CreateOrg200Response {
    pub fn new(message: String, org_id: i64) -> CreateOrg200Response {
        CreateOrg200Response {
            message,
            org_id,
        }
    }
}

