/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateCorrelationResponseBody : CreateCorrelationResponse is the response struct for CreateCorrelationCommand
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCorrelationResponseBody {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Correlation>>,
}

impl CreateCorrelationResponseBody {
    /// CreateCorrelationResponse is the response struct for CreateCorrelationCommand
    pub fn new() -> CreateCorrelationResponseBody {
        CreateCorrelationResponseBody {
            message: None,
            result: None,
        }
    }
}

