/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// DataSourceRef : Ref to a DataSource instance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataSourceRef {
    /// The plugin type-id
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Specific datasource instance
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
}

impl DataSourceRef {
    /// Ref to a DataSource instance
    pub fn new() -> DataSourceRef {
        DataSourceRef {
            r#type: None,
            uid: None,
        }
    }
}

