/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteDashboardByUid200Response {
    /// ID Identifier of the deleted dashboard.
    #[serde(rename = "id")]
    pub id: i64,
    /// Message Message of the deleted dashboard.
    #[serde(rename = "message")]
    pub message: String,
    /// Title Title of the deleted dashboard.
    #[serde(rename = "title")]
    pub title: String,
}

impl DeleteDashboardByUid200Response {
    pub fn new(id: i64, message: String, title: String) -> DeleteDashboardByUid200Response {
        DeleteDashboardByUid200Response {
            id,
            message,
            title,
        }
    }
}

