/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendedReceiver {
    #[serde(rename = "email_configs", skip_serializing_if = "Option::is_none")]
    pub email_configs: Option<Box<models::EmailConfig>>,
    #[serde(rename = "grafana_managed_receiver", skip_serializing_if = "Option::is_none")]
    pub grafana_managed_receiver: Option<Box<models::PostableGrafanaReceiver>>,
    #[serde(rename = "opsgenie_configs", skip_serializing_if = "Option::is_none")]
    pub opsgenie_configs: Option<Box<models::OpsGenieConfig>>,
    #[serde(rename = "pagerduty_configs", skip_serializing_if = "Option::is_none")]
    pub pagerduty_configs: Option<Box<models::PagerdutyConfig>>,
    #[serde(rename = "pushover_configs", skip_serializing_if = "Option::is_none")]
    pub pushover_configs: Option<Box<models::PushoverConfig>>,
    #[serde(rename = "slack_configs", skip_serializing_if = "Option::is_none")]
    pub slack_configs: Option<Box<models::SlackConfig>>,
    #[serde(rename = "victorops_configs", skip_serializing_if = "Option::is_none")]
    pub victorops_configs: Option<Box<models::VictorOpsConfig>>,
    #[serde(rename = "webhook_configs", skip_serializing_if = "Option::is_none")]
    pub webhook_configs: Option<Box<models::WebhookConfig>>,
    #[serde(rename = "wechat_configs", skip_serializing_if = "Option::is_none")]
    pub wechat_configs: Option<Box<models::WechatConfig>>,
}

impl ExtendedReceiver {
    pub fn new() -> ExtendedReceiver {
        ExtendedReceiver {
            email_configs: None,
            grafana_managed_receiver: None,
            opsgenie_configs: None,
            pagerduty_configs: None,
            pushover_configs: None,
            slack_configs: None,
            victorops_configs: None,
            webhook_configs: None,
            wechat_configs: None,
        }
    }
}

