/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Extension : Extension represents the ASN.1 structure of the same name. See RFC 5280, section 4.2.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Extension {
    #[serde(rename = "Critical", skip_serializing_if = "Option::is_none")]
    pub critical: Option<bool>,
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<i64>>,
    #[serde(rename = "Value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Vec<i32>>,
}

impl Extension {
    /// Extension represents the ASN.1 structure of the same name. See RFC 5280, section 4.2.
    pub fn new() -> Extension {
        Extension {
            critical: None,
            id: None,
            value: None,
        }
    }
}

