/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// FieldTypeConfig : FieldTypeConfig has type specific configs, only one should be active at a time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldTypeConfig {
    #[serde(rename = "enum", skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<Box<models::EnumFieldConfig>>,
}

impl FieldTypeConfig {
    /// FieldTypeConfig has type specific configs, only one should be active at a time
    pub fn new() -> FieldTypeConfig {
        FieldTypeConfig {
            r#enum: None,
        }
    }
}

