/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSharingOptions200Response {
    #[serde(rename = "externalEnabled", skip_serializing_if = "Option::is_none")]
    pub external_enabled: Option<bool>,
    #[serde(rename = "externalSnapshotName", skip_serializing_if = "Option::is_none")]
    pub external_snapshot_name: Option<String>,
    #[serde(rename = "externalSnapshotURL", skip_serializing_if = "Option::is_none")]
    pub external_snapshot_url: Option<String>,
}

impl GetSharingOptions200Response {
    pub fn new() -> GetSharingOptions200Response {
        GetSharingOptions200Response {
            external_enabled: None,
            external_snapshot_name: None,
            external_snapshot_url: None,
        }
    }
}

