/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// MoveFolderCommand : MoveFolderCommand captures the information required by the folder service to move a folder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveFolderCommand {
    #[serde(rename = "parentUid", skip_serializing_if = "Option::is_none")]
    pub parent_uid: Option<String>,
}

impl MoveFolderCommand {
    /// MoveFolderCommand captures the information required by the folder service to move a folder.
    pub fn new() -> MoveFolderCommand {
        MoveFolderCommand {
            parent_uid: None,
        }
    }
}

