/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PatchQueryCommentInQueryHistoryCommand : PatchQueryCommentInQueryHistoryCommand is the command for updating comment for query in query history
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchQueryCommentInQueryHistoryCommand {
    /// Updated comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl PatchQueryCommentInQueryHistoryCommand {
    /// PatchQueryCommentInQueryHistoryCommand is the command for updating comment for query in query history
    pub fn new() -> PatchQueryCommentInQueryHistoryCommand {
        PatchQueryCommentInQueryHistoryCommand {
            comment: None,
        }
    }
}

