/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostableGrafanaRule {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::AlertQuery>>,
    #[serde(rename = "exec_err_state", skip_serializing_if = "Option::is_none")]
    pub exec_err_state: Option<ExecErrState>,
    #[serde(rename = "is_paused", skip_serializing_if = "Option::is_none")]
    pub is_paused: Option<bool>,
    #[serde(rename = "no_data_state", skip_serializing_if = "Option::is_none")]
    pub no_data_state: Option<NoDataState>,
    #[serde(rename = "notification_settings", skip_serializing_if = "Option::is_none")]
    pub notification_settings: Option<Box<models::AlertRuleNotificationSettings>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
}

impl PostableGrafanaRule {
    pub fn new() -> PostableGrafanaRule {
        PostableGrafanaRule {
            condition: None,
            data: None,
            exec_err_state: None,
            is_paused: None,
            no_data_state: None,
            notification_settings: None,
            title: None,
            uid: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExecErrState {
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "Alerting")]
    Alerting,
    #[serde(rename = "Error")]
    Error,
}

impl Default for ExecErrState {
    fn default() -> ExecErrState {
        Self::Ok
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NoDataState {
    #[serde(rename = "Alerting")]
    Alerting,
    #[serde(rename = "NoData")]
    NoData,
    #[serde(rename = "OK")]
    Ok,
}

impl Default for NoDataState {
    fn default() -> NoDataState {
        Self::Alerting
    }
}

