/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// SilenceStatus : SilenceStatus silence status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SilenceStatus {
    /// state
    #[serde(rename = "state")]
    pub state: State,
}

impl SilenceStatus {
    /// SilenceStatus silence status
    pub fn new(state: State) -> SilenceStatus {
        SilenceStatus {
            state,
        }
    }
}
/// state
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "[expired active pending]")]
    LeftSquareBracketExpiredActivePendingRightSquareBracket,
}

impl Default for State {
    fn default() -> State {
        Self::LeftSquareBracketExpiredActivePendingRightSquareBracket
    }
}

