/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ThresholdsConfig : ThresholdsConfig setup thresholds
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThresholdsConfig {
    /// ThresholdsMode absolute or percentage
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// Must be sorted by 'value', first value is always -Infinity
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::Threshold>>,
}

impl ThresholdsConfig {
    /// ThresholdsConfig setup thresholds
    pub fn new() -> ThresholdsConfig {
        ThresholdsConfig {
            mode: None,
            steps: None,
        }
    }
}

