/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UserToken : UserToken represents a user token
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserToken {
    #[serde(rename = "AuthToken", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<String>,
    #[serde(rename = "AuthTokenSeen", skip_serializing_if = "Option::is_none")]
    pub auth_token_seen: Option<bool>,
    #[serde(rename = "ClientIp", skip_serializing_if = "Option::is_none")]
    pub client_ip: Option<String>,
    #[serde(rename = "CreatedAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "PrevAuthToken", skip_serializing_if = "Option::is_none")]
    pub prev_auth_token: Option<String>,
    #[serde(rename = "RevokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<i64>,
    #[serde(rename = "RotatedAt", skip_serializing_if = "Option::is_none")]
    pub rotated_at: Option<i64>,
    #[serde(rename = "SeenAt", skip_serializing_if = "Option::is_none")]
    pub seen_at: Option<i64>,
    #[serde(rename = "UnhashedToken", skip_serializing_if = "Option::is_none")]
    pub unhashed_token: Option<String>,
    #[serde(rename = "UpdatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    #[serde(rename = "UserAgent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
}

impl UserToken {
    /// UserToken represents a user token
    pub fn new() -> UserToken {
        UserToken {
            auth_token: None,
            auth_token_seen: None,
            client_ip: None,
            created_at: None,
            id: None,
            prev_auth_token: None,
            revoked_at: None,
            rotated_at: None,
            seen_at: None,
            unhashed_token: None,
            updated_at: None,
            user_agent: None,
            user_id: None,
        }
    }
}

