/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WechatConfig {
    #[serde(rename = "agent_id", skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    #[serde(rename = "api_secret", skip_serializing_if = "Option::is_none")]
    pub api_secret: Option<String>,
    #[serde(rename = "api_url", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<Box<models::Url>>,
    #[serde(rename = "corp_id", skip_serializing_if = "Option::is_none")]
    pub corp_id: Option<String>,
    #[serde(rename = "http_config", skip_serializing_if = "Option::is_none")]
    pub http_config: Option<Box<models::HttpClientConfig>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "message_type", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<String>,
    #[serde(rename = "send_resolved", skip_serializing_if = "Option::is_none")]
    pub send_resolved: Option<bool>,
    #[serde(rename = "to_party", skip_serializing_if = "Option::is_none")]
    pub to_party: Option<String>,
    #[serde(rename = "to_tag", skip_serializing_if = "Option::is_none")]
    pub to_tag: Option<String>,
    #[serde(rename = "to_user", skip_serializing_if = "Option::is_none")]
    pub to_user: Option<String>,
}

impl WechatConfig {
    pub fn new() -> WechatConfig {
        WechatConfig {
            agent_id: None,
            api_secret: None,
            api_url: None,
            corp_id: None,
            http_config: None,
            message: None,
            message_type: None,
            send_resolved: None,
            to_party: None,
            to_tag: None,
            to_user: None,
        }
    }
}

