services:
  grafana:
    image: grafana/grafana:10.3.3
    user: "${GRAFANA_USER_ID:-1000:1000}"
    volumes:
      - ./grafana-data:/var/lib/grafana # Persists Grafana data
      - ./grafana.ini:/etc/grafana/grafana.ini # Optional: Custom Grafana configuration
      - ../jwt_keys/grafana.key.pub:/etc/grafana/public-key.pem # Optional: Public key for JWT
    ports:
      - '3005:3000'
    restart: unless-stopped
