{
 "title": "Test_App",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (geo_location).lat AS latitude,\n  (geo_location).lon AS longitude,\n  COUNT(*) AS count\nFROM\n  connection_events\nWHERE\n  (geo_location).lat IS NOT NULL AND\n  (geo_location).lon IS NOT NULL\nGROUP BY\n  (geo_location).lat, (geo_location).lon\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "App connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_app_connection_count as connections, 'daily' AS metric\nFROM daily_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hourly_bucket as time, hourly_app_connection_count as connections, 'hourly' AS metric\nFROM hourly_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hourly_bucket)\nUNION ALL\n-- Use raw data (minute intervals) intervals between 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_app_connection_count as connections, '15min' AS metric\nFROM quarter_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_clients_connection_count as connections, 'daily' AS metric\nFROM daily_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hourly_bucket as time, hourly_clients_connection_count as connections, 'hourly' AS metric\nFROM hourly_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hourly_bucket)\nUNION ALL\n-- Use raw data (minute intervals) intervals between 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_clients_connection_count as connections, '15min' AS metric\nFROM quarter_connection_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT ra.app_name, ds.daily_bucket as time, ds.daily_active_users as active_users, 'daily' AS metric\nFROM daily_sessions_stats_per_app ds\nJOIN registered_apps ra ON ds.app_id = ra.app_id\nWHERE ds.app_id = '${__dashboard.uid}'\nAND $__timeFilter(ds.daily_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sessions Opened",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT ra.app_name, ds.daily_bucket as time, ds.daily_sessions_opened as sessions_opened, 'daily' AS metric\nFROM daily_sessions_stats_per_app ds\nJOIN registered_apps ra ON ds.app_id = ra.app_id\nWHERE ds.app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(ds.daily_bucket)\n\nUNION ALL\n\n-- Hourly aggregate for intervals between 3 and 14 days\nSELECT ra.app_name, hs.hourly_bucket as time, hs.hourly_sessions_opened as sessions_opened, 'hourly' AS metric\nFROM hourly_sessions_stats_per_app hs\nJOIN registered_apps ra ON hs.app_id = ra.app_id\nWHERE hs.app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hs.hourly_bucket)\n\nUNION ALL\n\n-- Use raw data (minute intervals) for intervals between 0 and 3 days\nSELECT ra.app_id, qs.quarter_bucket as time, qs.quarter_app_connection_count as connections, '15min' AS metric\nFROM quarter_connection_stats_per_app qs\nJOIN registered_apps ra ON qs.app_id = ra.app_id\nWHERE qs.app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(qs.quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sign Message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_sign_message_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_sign_message_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_sign_message_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sign And Send Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_sign_and_send_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_sign_and_send_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_sign_and_send_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sign Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_sign_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_sign_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_sign_transaction_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Change Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT app_id, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_change_network_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT app_id, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_change_network_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT app_id, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_change_network_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Change Wallet Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n    app_id, \n    wallet_name,\n    time, \n    SUM(success_requests) AS success_requests, \n    SUM(failed_requests) AS failed_requests, \n    metric\nFROM (\n    SELECT \n        app_id, \n        wallet_name, \n        daily_bucket AS time, \n        daily_successful_requests AS success_requests, \n        daily_unsuccessful_requests AS failed_requests, \n        'daily' AS metric\n    FROM \n        daily_events_change_wallet_stats_per_app\n    WHERE \n        app_id = '${__dashboard.uid}' AND \n        $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND \n        $__timeFilter(daily_bucket)\n    \n    UNION ALL\n\n    SELECT \n        app_id, \n        wallet_name, \n        hour_bucket AS time, \n        hour_successful_requests AS success_requests, \n        hour_unsuccessful_requests AS failed_requests, \n        'hourly' AS metric\n    FROM \n        hour_events_change_wallet_stats_per_app\n    WHERE \n        app_id = '${__dashboard.uid}' AND \n        $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND \n        $__timeFilter(hour_bucket)\n    \n    UNION ALL\n\n    SELECT \n        app_id, \n        wallet_name, \n        quarter_bucket AS time, \n        quarter_successful_requests AS success_requests, \n        quarter_unsuccessful_requests AS failed_requests, \n        '15min' AS metric\n    FROM \n        quarter_events_change_wallet_stats_per_app\n    WHERE \n        app_id = '${__dashboard.uid}' AND \n        $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND \n        $__timeFilter(quarter_bucket)\n) aggregated\nGROUP BY \n    app_id, \n    wallet_name,\n    time, \n    metric\nORDER BY \n    time;\n"
    }
   ]
  },
  {
   "title": "Successful requests summarization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  'sign_message' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_message' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_message' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL -------------------------------------------------------------------\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ------------------------------------------------------------------\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ---------------------------------------------------------------------\nSELECT\n  'change_network' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'change_network' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'change_network' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ---------------------------------------------------------------------\nSELECT\n  'change_wallet' as request_type,\n  app_id,\n  time,\n  SUM(success_requests) AS success_requests,\n  SUM(failed_requests) AS failed_requests,\n  metric\nFROM\n  (\n    SELECT\n      app_id,\n      wallet_name,\n      daily_bucket AS time,\n      daily_successful_requests AS success_requests,\n      daily_unsuccessful_requests AS failed_requests,\n      'daily' AS metric\n    FROM\n      daily_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n      AND $__timeFilter(daily_bucket)\n    UNION\n    ALL\n    SELECT\n      app_id,\n      wallet_name,\n      hour_bucket AS time,\n      hour_successful_requests AS success_requests,\n      hour_unsuccessful_requests AS failed_requests,\n      'hourly' AS metric\n    FROM\n      hour_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n      AND '14 days' :: interval\n      AND $__timeFilter(hour_bucket)\n    UNION\n    ALL\n    SELECT\n      app_id,\n      wallet_name,\n      quarter_bucket AS time,\n      quarter_successful_requests AS success_requests,\n      quarter_unsuccessful_requests AS failed_requests,\n      '15min' AS metric\n    FROM\n      quarter_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n      AND $__timeFilter(quarter_bucket)\n  ) aggregated\nGROUP BY\n  app_id,\n  wallet_name,\n  time,\n  metric\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Failed requests summarization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  'sign_message' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_message' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_message' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_message_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL -------------------------------------------------------------------\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_transaction' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ------------------------------------------------------------------\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'sign_and_send_transaction' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_sign_and_send_transaction_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ---------------------------------------------------------------------\nSELECT\n  'change_network' as request_type,\n  app_id,\n  daily_bucket as time,\n  daily_successful_requests as success_requests,\n  daily_unsuccessful_requests as failed_requests,\n  'daily' AS metric\nFROM\n  daily_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n  AND $__timeFilter(daily_bucket)\nUNION\nALL -- Use hourly aggregate for intervals between 3 and 14 days\nSELECT\n  'change_network' as request_type,\n  app_id,\n  hour_bucket as time,\n  hour_successful_requests as success_requests,\n  hour_unsuccessful_requests as failed_requests,\n  'hourly' AS metric\nFROM\n  hour_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n  AND '14 days' :: interval\n  AND $__timeFilter(hour_bucket)\nUNION\nALL -- Use 15 minutes interval 0 and 3 days\nSELECT\n  'change_network' as request_type,\n  app_id,\n  quarter_bucket as time,\n  quarter_successful_requests as quarter_requests,\n  quarter_unsuccessful_requests as failed_requests,\n  '15min' AS metric\nFROM\n  quarter_events_change_network_stats_per_app\nWHERE\n  app_id = '${__dashboard.uid}'\n  AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n  AND $__timeFilter(quarter_bucket)\nUNION\nALL ---------------------------------------------------------------------\nSELECT\n  'change_wallet' as request_type,\n  app_id,\n  time,\n  SUM(success_requests) AS success_requests,\n  SUM(failed_requests) AS failed_requests,\n  metric\nFROM\n  (\n    SELECT\n      app_id,\n      wallet_name,\n      daily_bucket AS time,\n      daily_successful_requests AS success_requests,\n      daily_unsuccessful_requests AS failed_requests,\n      'daily' AS metric\n    FROM\n      daily_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp > '14 days' :: interval\n      AND $__timeFilter(daily_bucket)\n    UNION\n    ALL\n    SELECT\n      app_id,\n      wallet_name,\n      hour_bucket AS time,\n      hour_successful_requests AS success_requests,\n      hour_unsuccessful_requests AS failed_requests,\n      'hourly' AS metric\n    FROM\n      hour_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp BETWEEN '3 days' :: interval\n      AND '14 days' :: interval\n      AND $__timeFilter(hour_bucket)\n    UNION\n    ALL\n    SELECT\n      app_id,\n      wallet_name,\n      quarter_bucket AS time,\n      quarter_successful_requests AS success_requests,\n      quarter_unsuccessful_requests AS failed_requests,\n      '15min' AS metric\n    FROM\n      quarter_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo() :: timestamp - $__timeFrom() :: timestamp < '3 days' :: interval\n      AND $__timeFilter(quarter_bucket)\n  ) aggregated\nGROUP BY\n  app_id,\n  wallet_name,\n  time,\n  metric\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Requests sumarization",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  SUM(success_requests) AS success_requests,\n  SUM(failed_requests) AS failed_requests,\n  metric\nFROM (\n  SELECT\n    'sign_message' AS request_type,\n    app_id,\n    daily_bucket AS time,\n    daily_successful_requests AS success_requests,\n    daily_unsuccessful_requests AS failed_requests,\n    'daily' AS metric\n  FROM\n    daily_events_sign_message_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval\n    AND $__timeFilter(daily_bucket)\n  UNION ALL\n  SELECT\n    'sign_message' AS request_type,\n    app_id,\n    hour_bucket AS time,\n    hour_successful_requests AS success_requests,\n    hour_unsuccessful_requests AS failed_requests,\n    'hourly' AS metric\n  FROM\n    hour_events_sign_message_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval\n    AND $__timeFilter(hour_bucket)\n  UNION ALL\n  SELECT\n    'sign_message' AS request_type,\n    app_id,\n    quarter_bucket AS time,\n    quarter_successful_requests AS success_requests,\n    quarter_unsuccessful_requests AS failed_requests,\n    '15min' AS metric\n  FROM\n    quarter_events_sign_message_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval\n    AND $__timeFilter(quarter_bucket)\n  UNION ALL\n  SELECT\n    'sign_transaction' AS request_type,\n    app_id,\n    daily_bucket AS time,\n    daily_successful_requests AS success_requests,\n    daily_unsuccessful_requests AS failed_requests,\n    'daily' AS metric\n  FROM\n    daily_events_sign_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval\n    AND $__timeFilter(daily_bucket)\n  UNION ALL\n  SELECT\n    'sign_transaction' AS request_type,\n    app_id,\n    hour_bucket AS time,\n    hour_successful_requests AS success_requests,\n    hour_unsuccessful_requests AS failed_requests,\n    'hourly' AS metric\n  FROM\n    hour_events_sign_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval\n    AND $__timeFilter(hour_bucket)\n  UNION ALL\n  SELECT\n    'sign_transaction' AS request_type,\n    app_id,\n    quarter_bucket AS time,\n    quarter_successful_requests AS success_requests,\n    quarter_unsuccessful_requests AS failed_requests,\n    '15min' AS metric\n  FROM\n    quarter_events_sign_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval\n    AND $__timeFilter(quarter_bucket)\n  UNION ALL\n  SELECT\n    'sign_and_send_transaction' AS request_type,\n    app_id,\n    daily_bucket AS time,\n    daily_successful_requests AS success_requests,\n    daily_unsuccessful_requests AS failed_requests,\n    'daily' AS metric\n  FROM\n    daily_events_sign_and_send_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval\n    AND $__timeFilter(daily_bucket)\n  UNION ALL\n  SELECT\n    'sign_and_send_transaction' AS request_type,\n    app_id,\n    hour_bucket AS time,\n    hour_successful_requests AS success_requests,\n    hour_unsuccessful_requests AS failed_requests,\n    'hourly' AS metric\n  FROM\n    hour_events_sign_and_send_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval\n    AND $__timeFilter(hour_bucket)\n  UNION ALL\n  SELECT\n    'sign_and_send_transaction' AS request_type,\n    app_id,\n    quarter_bucket AS time,\n    quarter_successful_requests AS success_requests,\n    quarter_unsuccessful_requests AS failed_requests,\n    '15min' AS metric\n  FROM\n    quarter_events_sign_and_send_transaction_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval\n    AND $__timeFilter(quarter_bucket)\n  UNION ALL\n  SELECT\n    'change_network' AS request_type,\n    app_id,\n    daily_bucket AS time,\n    daily_successful_requests AS success_requests,\n    daily_unsuccessful_requests AS failed_requests,\n    'daily' AS metric\n  FROM\n    daily_events_change_network_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval\n    AND $__timeFilter(daily_bucket)\n  UNION ALL\n  SELECT\n    'change_network' AS request_type,\n    app_id,\n    hour_bucket AS time,\n    hour_successful_requests AS success_requests,\n    hour_unsuccessful_requests AS failed_requests,\n    'hourly' AS metric\n  FROM\n    hour_events_change_network_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval\n    AND $__timeFilter(hour_bucket)\n  UNION ALL\n  SELECT\n    'change_network' AS request_type,\n    app_id,\n    quarter_bucket AS time,\n    quarter_successful_requests AS success_requests,\n    quarter_unsuccessful_requests AS failed_requests,\n    '15min' AS metric\n  FROM\n    quarter_events_change_network_stats_per_app\n  WHERE\n    app_id = '${__dashboard.uid}'\n    AND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval\n    AND $__timeFilter(quarter_bucket)\n  UNION ALL\n  SELECT\n    'change_wallet' AS request_type,\n    app_id,\n    time,\n    SUM(success_requests) AS success_requests,\n    SUM(failed_requests) AS failed_requests,\n    metric\n  FROM (\n    SELECT\n      app_id,\n      wallet_name,\n      daily_bucket AS time,\n      daily_successful_requests AS success_requests,\n      daily_unsuccessful_requests AS failed_requests,\n      'daily' AS metric\n    FROM\n      daily_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval\n      AND $__timeFilter(daily_bucket)\n    UNION ALL\n    SELECT\n      app_id,\n      wallet_name,\n      hour_bucket AS time,\n      hour_successful_requests AS success_requests,\n      hour_unsuccessful_requests AS failed_requests,\n      'hourly' AS metric\n    FROM\n      hour_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval\n      AND $__timeFilter(hour_bucket)\n    UNION ALL\n    SELECT\n      app_id,\n      wallet_name,\n      quarter_bucket AS time,\n      quarter_successful_requests AS success_requests,\n      quarter_unsuccessful_requests AS failed_requests,\n      '15min' AS metric\n    FROM\n      quarter_events_change_wallet_stats_per_app\n    WHERE\n      app_id = '${__dashboard.uid}'\n      AND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval\n      AND $__timeFilter(quarter_bucket)\n  ) aggregated\n  GROUP BY\n    app_id,\n    wallet_name,\n    time,\n    metric\n) combined\nGROUP BY\n  time,\n  metric\nORDER BY\n  time;\n"
    }
   ]
  },
  {
   "title": "Sessions | Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT daily_bucket as time, daily_mobile_sessions as mobile_sessions, daily_web_sessions as web_sessions, daily_unknown_sessions as unknown_sessions, 'daily' AS metric\nFROM daily_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT hour_bucket as time, hour_mobile_sessions as mobile_sessions, hour_web_sessions as web_sessions, hour_unknown_sessions as unknown_sessions,  'hourly' AS metric\nFROM hour_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT quarter_bucket as time, quarter_mobile_sessions as mobile_sessions, quarter_web_sessions as web_sessions, quarter_unknown_sessions as unknown_sessions,  '15min' AS metric\nFROM quarter_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Mobile Sessions | System type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT system_type, daily_bucket as time, daily_system as system_type_count, 'daily' AS metric\nFROM daily_events_app_connect_system_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\n    UNION ALL\nSELECT system_type, hour_bucket as time, hour_system as system_type_count,  'hourly' AS metric\nFROM hour_events_app_connect_system_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\n    UNION ALL\nSELECT system_type, quarter_bucket as time, quarter_system as system_type_count,  '15min' AS metric\nFROM quarter_events_app_connect_system_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Web Sessions | Browser",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT browser, daily_bucket as time, daily_browser as browser_count, 'daily' AS metric\nFROM daily_events_app_connect_browser_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\n    UNION ALL\nSELECT browser, hour_bucket as time, hour_browser as browser_count,  'hourly' AS metric\nFROM hour_events_app_connect_browser_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\n    UNION ALL\nSELECT browser, quarter_bucket as time, quarter_browser as browser_count,  '15min' AS metric\nFROM quarter_events_app_connect_browser_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Client Connections | Wallets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT wallet_name, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_client_connect_wallet_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT wallet_name, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_client_connect_wallet_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT wallet_name, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_client_connect_wallet_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sessions | Connection Type Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT daily_bucket as time, daily_mobile_sessions as mobile, daily_web_sessions as web, daily_unknown_sessions as unknown, 'daily' AS metric\nFROM daily_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT hour_bucket as time, hour_mobile_sessions as mobile, hour_web_sessions as web, hour_unknown_sessions as unknown, 'hourly' AS metric\nFROM hour_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT quarter_bucket as time, quarter_mobile_sessions as mobile, quarter_web_sessions as web, quarter_unknown_sessions as unknown,  '15min' AS metric\nFROM quarter_events_app_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Web Sessions | Os type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT os, daily_bucket as time, daily_os as os_count, 'daily' AS metric\nFROM daily_events_app_connect_os_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\n    UNION ALL\nSELECT os, hour_bucket as time, hour_os as os_count,  'hourly' AS metric\nFROM hour_events_app_connect_os_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\n    UNION ALL\nSELECT os, quarter_bucket as time, quarter_os as os_count,  '15min' AS metric\nFROM quarter_events_app_connect_os_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Client Connections | Session Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT session_type, daily_bucket as time, daily_successful_requests as success_requests, daily_unsuccessful_requests as failed_requests, 'daily' AS metric\nFROM daily_events_client_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\nUNION ALL\n-- Use hourly aggregate for intervals between 3 and 14 days\nSELECT session_type, hour_bucket as time, hour_successful_requests as success_requests, hour_unsuccessful_requests as failed_requests,  'hourly' AS metric\nFROM hour_events_client_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\nUNION ALL\n-- Use 15 minutes interval 0 and 3 days\nSELECT session_type, quarter_bucket as time, quarter_successful_requests as quarter_requests, quarter_unsuccessful_requests as failed_requests,  '15min' AS metric\nFROM quarter_events_client_connect_session_type_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Language",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT lang, daily_bucket as time, daily_language as lang_count, 'daily' AS metric\nFROM daily_events_app_connect_language_stats_per_app\nWHERE app_id = '${__dashboard.uid}'\nAND $__timeTo()::timestamp - $__timeFrom()::timestamp > '14 days'::interval AND $__timeFilter(daily_bucket)\n    UNION ALL\nSELECT lang, hour_bucket as time, hour_language as lang_count,  'hourly' AS metric\nFROM hour_events_app_connect_language_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp BETWEEN '3 days'::interval AND '14 days'::interval AND $__timeFilter(hour_bucket)\n    UNION ALL\nSELECT lang, quarter_bucket as time, quarter_language as lang_count,  '15min' AS metric\nFROM quarter_events_app_connect_language_stats_per_app\nWHERE app_id = '${__dashboard.uid}'  \nAND $__timeTo()::timestamp - $__timeFrom()::timestamp < '3 days'::interval AND  $__timeFilter(quarter_bucket)\nORDER BY time\n"
    }
   ]
  }
 ]
}