// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppInfo { team_id: string, app_id: string, app_name: string, registered_at: string, whitelisted_domains: Array<string>, ack_public_keys: Array<string>, }