// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectRequest } from "./ConnectRequest";
import type { GetInfoRequest } from "./GetInfoRequest";
import type { GetPendingRequestsRequest } from "./GetPendingRequestsRequest";
import type { Reject } from "./Reject";
import type { SignMessagesEventReply } from "./SignMessagesEventReply";
import type { SignTransactionsEventReply } from "./SignTransactionsEventReply";

export type ClientToServer = { type: "ConnectRequest" } & ConnectRequest | { type: "GetInfoRequest" } & GetInfoRequest | { type: "SignTransactionsEventReply" } & SignTransactionsEventReply | { type: "SignMessagesEventReply" } & SignMessagesEventReply | { type: "GetPendingRequestsRequest" } & GetPendingRequestsRequest | { type: "Reject" } & Reject;