// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConnectEvent } from "./AppConnectEvent";
import type { AppDisconnectEvent } from "./AppDisconnectEvent";
import type { ClientConnectInitEvent } from "./ClientConnectInitEvent";
import type { ClientConnectResolveEvent } from "./ClientConnectResolveEvent";
import type { ClientDisconnectEvent } from "./ClientDisconnectEvent";
import type { NewRequestEvent } from "./NewRequestEvent";
import type { RequestResolvedEvent } from "./RequestResolvedEvent";

export type EventData = { type: "AppConnect" } & AppConnectEvent | { type: "AppDisconnect" } & AppDisconnectEvent | { type: "ClientConnectInit" } & ClientConnectInitEvent | { type: "ClientConnectResolve" } & ClientConnectResolveEvent | { type: "ClientDisconnect" } & ClientDisconnectEvent | { type: "NewRequest" } & NewRequestEvent | { type: "RequestResolved" } & RequestResolvedEvent;