// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingRequest } from "./PendingRequest";

export interface GetPendingRequestsResponse { responseId: string, requests: Array<PendingRequest>, }