// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMetadata } from "./AppMetadata";
import type { Network } from "./Network";
import type { SessionStatus } from "./SessionStatus";
import type { Version } from "./Version";

export interface HttpGetSessionInfoResponse { status: SessionStatus, persistent: boolean, version: Version, network: Network, appMetadata: AppMetadata, }