// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface JoinedTeam { team_id: string, team_name: string, creator_email: string, created_at: string, joined_at: string, personal: boolean, }