// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMetadata } from "./AppMetadata";
import type { Device } from "./Device";
import type { Network } from "./Network";

export interface NotificationPayload { token: string, network: Network, sessionId: string, appMetadata: AppMetadata, device: Device, request: string, requestId: string, }