// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageToSign } from "./MessageToSign";

export interface SignMessagesEvent { requestId: string, messages: Array<MessageToSign>, metadata?: string, }