// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestFail } from "./RequestFail";

export interface SignTransactionResolveEvent { sessionId: string, requestId: string, txHash: string | null, failureReason?: RequestFail, }