// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivilegeLevel } from "./PrivilegeLevel";

export interface TeamUserPrivilege { appId: string, userEmail: string, privilege: PrivilegeLevel, }