// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppInfo { teamId: string, appId: string, appName: string, registeredAt: string, whitelistedDomains: Array<string>, ackPublicKeys: Array<string>, }