// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HttpGetPendingRequestRequest { clientId: string, sessionId: string, requestId: string, }