// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Network } from "./Network";
import type { Version } from "./Version";

export interface InitializeRequest { responseId: string, persistent: boolean, appName: string, appDescription: string | null, appIcon: string | null, network: Network, version: Version, additionalInfo: string | null, persistentSessionId: string | null, }