// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AckMessage } from "./AckMessage";
import type { AppDisconnectedEvent } from "./AppDisconnectedEvent";
import type { ClientInitializeResponse } from "./ClientInitializeResponse";
import type { ConnectResponse } from "./ConnectResponse";
import type { ErrorMessage } from "./ErrorMessage";
import type { GetInfoResponse } from "./GetInfoResponse";
import type { GetPendingRequestsResponse } from "./GetPendingRequestsResponse";
import type { NewPayloadEvent } from "./NewPayloadEvent";

export type ServerToClient = { type: "ClientInitializeResponse" } & ClientInitializeResponse | { type: "GetInfoResponse" } & GetInfoResponse | { type: "ConnectResponse" } & ConnectResponse | { type: "NewPayloadEvent" } & NewPayloadEvent | { type: "AppDisconnectedEvent" } & AppDisconnectedEvent | { type: "GetPendingRequestsResponse" } & GetPendingRequestsResponse | { type: "ErrorMessage" } & ErrorMessage | { type: "AckMessage" } & AckMessage;