// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Subscription { subscription_type: string, valid_from: bigint, valid_till: bigint, }