// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TeamMetadata { creatorEmail: string, teamId: string, teamName: string, personalTeam: boolean, createdAt: string, }