name: connect-test-production.yml

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    timeout-minutes: 10
    runs-on: [testing]
    steps:
      - name: Fix permissions
        continue-on-error: true
        run: |
          echo ${{secrets.TESTING_LAPTOP_PASSWORD}} | sudo -S chmod 777 -R  ~/runners/${{ runner.name }}/_work/connect/connect
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        continue-on-error: true
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          pnpm install
        working-directory: ./sdk
      - name: test base production
        run: |
          pnpm test:production
        working-directory: ./sdk/packages/base
      - name: test solana production
        run: |
          pnpm test:production
        working-directory: ./sdk/packages/solana
      - name: test sui production
        run: |
          pnpm test:production
        working-directory: ./sdk/packages/sui
